#version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: vinay
      POSTGRES_PASSWORD: root
      POSTGRES_DB: weather
    ports:
      - "5433:5432"  # Correct internal port mapping
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis:latest

  airflow-webserver:
    image: apache/airflow:2.6.1
    depends_on:
      - postgres
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://vinay:root@postgres/weather
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://vinay:root@postgres/weather
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8090:8080"  # Webserver mapped to 8090
    command: ["bash", "-c", "airflow db init && airflow webserver"]  # Ensure db init runs

  airflow-scheduler:
    image: apache/airflow:2.6.1
    depends_on:
      - airflow-webserver
      - postgres
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://vinay:root@postgres/weather
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://vinay:root@postgres/weather
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./data:/opt/airflow/data
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler

  airflow-worker:
    image: apache/airflow:2.6.1
    depends_on:
      - redis
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://vinay:root@postgres/weather
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://vinay:root@postgres/weather
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./data:/opt/airflow/data
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: celery worker

volumes:
  postgres_db:
